version: "2"

networks:
  xtbfront-net:
    driver: bridge

services:
  xtbfront-api:
    build:
      context: ./back/xtbfront
      dockerfile: Dockerfile
    restart: always
    container_name: xtbfront-api
    ports:
      - 4000:4000
    env_file: .xtbfront-api.env
    networks:
      - xtbfront-net

  xtbfront-web:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    container_name: xtbfront-web
    ports:
      - 8000:80
    volumes:
      - ./front/public/config.env.js:/usr/share/nginx/html/config.env.js
    networks:
      - xtbfront-net
